services:
    
  db: 
    build: ./ERGIA_db

    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/POSTGRES_USER) -d $(cat /run/secrets/POSTGRES_DB)"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/posgres
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    networks:
      - back_tier

  backend:
      build: ./ERGIA_back
      depends_on:
        db:
          condition: service_healthy
          restart: true
      networks:
        - back_tier
        - front_tier
        
      secrets:
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_USER
      
      expose:
        - "5000"

  frontend: 
    build: ./ERGIA_front
    ports:
      - "80:80"
    networks:
      - front_tier
    depends_on:
      - backend

networks:
  back_tier:
  front_tier:

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/db_password.txt
  POSTGRES_DB:
    file: ./secrets/db_name.txt
  POSTGRES_USER:
    file: ./secrets/db_user.txt

volumes:
  db_postgres:
    driver: local